# https://clangd.llvm.org/config
CompileFlags:
  Add:  []
  Compiler: clang++  
Style:
  FullyQualifiedNamespaces: NO
Diagnostics:
  Suppress: Wunused
  ClangTidy:
    Add: modernize*
    Remove: modernize-use-trailing-return-type
  UnusedIncludes: Strict
InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
Hover:
  ShowAKA: Yes
