# https://clangd.llvm.org/config
CompileFlags:
  Add: [ --target=x86_64-w64-windows-gnu ,std=c++2a, -Wall, -Wno-unused-function, -Wno-unused-macros,-Wno-unused-member-function,-Wno-unused-template]             # treat all files as C++, enable more warnings
  Remove: []
  Compiler: clang++  
Style:
  FullyQualifiedNamespaces: NO
Diagnostics:
  Suppress: Wunused
  ClangTidy:
    Add: modernize*
    Remove: modernize-use-trailing-return-type
  CheckOptions:
    readability-identifier-naming.VariableCase: CamelCase
  UnusedIncludes: Strict
InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
Hover:
  ShowAKA: Yes
